### ISSUE TITLE
--dir seems to disable --start-page

### ISSUE THREAD

**Issue by nicklawls** [wking-io/elm-serve#7]
If I run this command

`elm-serve -p 8001 -s deploy/static/index.html`

`localhost:8001/` serves `index.html`

However, when running this

`elm-serve src/Main.elm -p 8001 -s deploy/static/index.html -d deploy`

`localhost:8001` serves "File Not Found"

I will try to come back through and provide a minimal directory setup that reproduces this

**Comment by wking-io** [comment]
Resolved in elm-live repo
